# Generated by Django 5.2.13 on 2026-08-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField()),
                ('durata_minuti', models.PositiveIntegerField(default=60)),
                ('stato', models.CharField(default='Confermata', max_length=20)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='utenti.paziente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='utenti.terapeuta')),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['data_ora'],
                'constraints': [models.UniqueConstraint(fields=('terapeuta', 'data_ora'), name='unica_seduta_terapeuta')],
            },
        ),
    ]
