# Generated by Django 5.2.13 on 2026-08-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
        ('utenti', '0002_branca_specializzazione_remove_paziente_cf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora_inizio', models.DateTimeField()),
                ('data_ora_fine', models.DateTimeField()),
                ('motivazione', models.CharField(blank=True, max_length=100, null=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assenze', to='utenti.terapeuta')),
            ],
            options={
                'verbose_name': 'Assenza',
                'verbose_name_plural': 'Assenze',
                'ordering': ['data_ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilita', to='utenti.terapeuta')),
            ],
            options={
                'verbose_name': 'Disponibilità',
                'verbose_name_plural': 'Disponibilità',
                'ordering': ['giorno', 'ora_inizio'],
                'constraints': [models.UniqueConstraint(fields=('terapeuta', 'giorno', 'ora_inizio', 'ora_fine'), name='unica_disponibilita')],
            },
        ),
    ]
