# Generated by Django 5.2.13 on 2026-08-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0002_assenza_disponibilita'),
        ('utenti', '0003_remove_terapeuta_branche_delete_branca'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disponibilita',
            name='unica_disponibilita',
        ),
        migrations.AddField(
            model_name='disponibilita',
            name='studio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilita', to='utenti.studio'),
        ),
        migrations.AddConstraint(
            model_name='disponibilita',
            constraint=models.UniqueConstraint(fields=('terapeuta', 'studio', 'giorno', 'ora_inizio', 'ora_fine'), name='unica_disponibilita'),
        ),
    ]
