# Generated by Django 5.2.13 on 2026-08-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_remove_disponibilita_unica_disponibilita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assenza',
            options={'ordering': ['data_inizio'], 'verbose_name': 'Assenza', 'verbose_name_plural': 'Assenze'},
        ),
        migrations.RemoveField(
            model_name='assenza',
            name='data_ora_fine',
        ),
        migrations.RemoveField(
            model_name='assenza',
            name='data_ora_inizio',
        ),
        migrations.AddField(
            model_name='assenza',
            name='data_fine',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='assenza',
            name='data_inizio',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('Attesa', 'Attesa'), ('Confermata', 'Confermata'), ('Completata', 'Completata'), ('Annullata', 'Annullata')], default='Attesa', max_length=20),
        ),
    ]
