# Generated by Django 5.2.13 on 2026-08-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0004_alter_assenza_options_remove_assenza_data_ora_fine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='stato',
        ),
    ]
