# Generated by Django 5.2.13 on 2026-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0005_remove_prenotazione_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='letta_da_medico',
            field=models.BooleanField(default=False),
        ),
    ]
