# Generated by Django 5.2.13 on 2026-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0006_prenotazione_letta_da_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('in_programma', 'In Programma'), ('cancellata', 'Cancellata')], default='in_programma', max_length=20),
        ),
    ]
