# Generated by Django 5.2.13 on 2026-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0007_prenotazione_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='nascosta_paziente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='nascosta_terapeuta',
            field=models.BooleanField(default=False),
        ),
    ]
