# Generated by Django 5.2.13 on 2026-08-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0008_prenotazione_nascosta_paziente_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prenotazione',
            name='unica_seduta_terapeuta',
        ),
    ]
