# Generated by Django 5.2.13 on 2026-08-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0009_remove_prenotazione_unica_seduta_terapeuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='descrizione',
            field=models.TextField(blank=True, help_text='Descrizione della seduta (opzionale)', null=True),
        ),
    ]
