# Generated by Django 5.2.13 on 2026-08-11 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Studio',
                'verbose_name_plural': 'Studi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CF', models.CharField(max_length=16, unique=True)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paziente',
                'verbose_name_plural': 'Pazienti',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('specializzazioni', models.JSONField(blank=True, default=list, null=True)),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terapeuti', to='utenti.studio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeuti',
                'ordering': ['id'],
            },
        ),
    ]
