# Generated by Django 5.2.13 on 2026-08-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Branca',
                'verbose_name_plural': 'Branche',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Specializzazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Specializzazione',
                'verbose_name_plural': 'Specializzazioni',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='paziente',
            name='CF',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='studio',
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='studi',
            field=models.ManyToManyField(blank=True, related_name='terapeuti', to='utenti.studio'),
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='specializzazioni',
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='branche',
            field=models.ManyToManyField(blank=True, related_name='terapeuti', to='utenti.branca'),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='specializzazioni',
            field=models.ManyToManyField(blank=True, related_name='terapeuti', to='utenti.specializzazione'),
        ),
    ]
