# Generated by Django 5.2.13 on 2026-08-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0002_branca_specializzazione_remove_paziente_cf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapeuta',
            name='branche',
        ),
        migrations.DeleteModel(
            name='Branca',
        ),
    ]
