# Generated by Django 5.2.13 on 2026-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0003_remove_terapeuta_branche_delete_branca'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziente',
            name='CF',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='pec',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
