# Generated by Django 5.2.13 on 2026-08-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0004_paziente_cf_terapeuta_pec_terapeuta_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartellaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('is_condivisa', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('cartella_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sottocartelle', to='utenti.cartellafile')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti_clinici/')),
                ('nome_originale', models.CharField(max_length=255)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('caricato_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cartella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='utenti.cartellafile')),
            ],
        ),
        migrations.CreateModel(
            name='RelazioneTerapeutica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paziente_puo_caricare_file', models.BooleanField(default=False)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.paziente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.terapeuta')),
            ],
            options={
                'unique_together': {('terapeuta', 'paziente')},
            },
        ),
        migrations.AddField(
            model_name='cartellafile',
            name='relazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelle', to='utenti.relazioneterapeutica'),
        ),
    ]
