# Generated by Django 5.2.13 on 2026-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0005_cartellafile_documento_relazioneterapeutica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='link_ordine',
            field=models.URLField(blank=True, null=True),
        ),
    ]
