# Generated by Django 5.2.13 on 2026-08-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0006_terapeuta_link_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziente',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profili/pazienti/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='foto_studio',
            field=models.ImageField(blank=True, null=True, upload_to='foto_studi/'),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profili/terapeuti/'),
        ),
    ]
