# Generated by Django 5.2.13 on 2026-08-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0007_paziente_foto_profilo_studio_foto_studio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paziente',
            name='foto_profilo',
        ),
    ]
