# Generated by Django 5.2.13 on 2026-09-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0008_remove_paziente_foto_profilo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartellafile',
            options={'verbose_name': 'Cartella', 'verbose_name_plural': 'Cartelle'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='relazioneterapeutica',
            options={'verbose_name': 'Relazione Terapeutica', 'verbose_name_plural': 'Relazioni Terapeutiche'},
        ),
        migrations.AddField(
            model_name='paziente',
            name='citta_residenza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
